---
# docker-compose.yml
version: '3.0'
volumes:
  track:
services:
  isbg:
    image: normannovaes/docker-isbg
    volumes:
      - track:/track
    environment:
      IMAPHOST: ${IMAPHOST}
      IMAPUSER: ${IMAPUSER}
      IMAPPASSWD: ${IMAPPASSWD}
      SPAMINBOX: ${SPAMINBOX}
      LEARNHAMBOXES: ${LEARNHAMBOXES}
      LEARNSPAMBOXES: ${LEARNSPAMBOXES}
      TRACKFILE: ${TRACKFILE}
